server:
  port: 2025

spring:
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      routes:
        - id: ProductService
          uri: lb://ProductService
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: ProductService
                fallbackuri: forward:/Productfallback

        - id: CustomerService
          uri: lb://CustomerService
          predicates:
            - Path=/Customer/**
          filters:
            - name: CircuitBreaker
              args:
                name: CustomerService
                fallbackuri: forward:/Customerfallback

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000